import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import RoadmapCard from "../components/RoadmapCard";
import api from "../services/api";

const getRoadmapStorageKey = () => {
  try {
    const user = JSON.parse(localStorage.getItem("user") || "{}");
    return `smarthire.learning-roadmap.${user?._id || "guest"}`;
  } catch (_error) {
    return "smarthire.learning-roadmap.guest";
  }
};

const readRoadmapCache = (key) => {
  try {
    const cached = JSON.parse(localStorage.getItem(key) || "{}");
    return {
      payload: cached?.payload || {},
      roadmap: Array.isArray(cached?.roadmap) ? cached.roadmap : [],
      warning: typeof cached?.warning === "string" ? cached.warning : "",
    };
  } catch (_error) {
    return { payload: {}, roadmap: [], warning: "" };
  }
};

function LearningRoadmap() {
  const location = useLocation();
  const navigate = useNavigate();
  const incomingPayload = useMemo(() => location.state || {}, [location.state]);
  const hasIncomingSkills = Array.isArray(incomingPayload?.missingSkills) && incomingPayload.missingSkills.length > 0;
  const storageKey = useMemo(() => getRoadmapStorageKey(), []);
  const cached = useMemo(() => readRoadmapCache(storageKey), [storageKey]);
  const [payload, setPayload] = useState(hasIncomingSkills ? incomingPayload : cached.payload || {});
  const [loading, setLoading] = useState(hasIncomingSkills);
  const [error, setError] = useState("");
  const [roadmap, setRoadmap] = useState(cached.roadmap || []);
  const [warning, setWarning] = useState(cached.warning || "");

  useEffect(() => {
    if (hasIncomingSkills) {
      setPayload(incomingPayload);
    }
  }, [incomingPayload, hasIncomingSkills]);

  useEffect(() => {
    const missingSkills = Array.isArray(payload?.missingSkills) ? payload.missingSkills : [];

    // On refresh, restore cached roadmap without forcing another AI call.
    if (!hasIncomingSkills) {
      setLoading(false);
      if (!missingSkills.length && !roadmap.length) {
        setError("No missing skills found. Analyze resume first.");
      } else {
        setError("");
      }
      return;
    }

    if (!missingSkills.length) {
      setLoading(false);
      setError("No missing skills found. Analyze resume first.");
      return;
    }

    const run = async () => {
      try {
        setLoading(true);
        setError("");
        const { data } = await api.post("/skills/roadmap-ai", {
          missingSkills,
          roleSkills: payload?.roleSkills || [],
          detectedSkills: payload?.detectedSkills || [],
          roleTitle: payload?.roleTitle || "Selected Role",
        });
        setRoadmap(data?.roadmap || []);
        setWarning(data?.warning || "");
      } catch (roadmapErr) {
        setError(roadmapErr?.response?.data?.message || "Could not generate roadmap.");
      } finally {
        setLoading(false);
      }
    };

    run();
  }, [payload, hasIncomingSkills]);

  useEffect(() => {
    if (!Array.isArray(payload?.missingSkills) || !payload.missingSkills.length || !roadmap.length) return;
    localStorage.setItem(
      storageKey,
      JSON.stringify({
        payload,
        roadmap,
        warning,
        updatedAt: new Date().toISOString(),
      })
    );
  }, [payload, roadmap, warning, storageKey]);

  const downloadRoadmap = () => {
    if (!roadmap.length) return;

    const roleTitle = payload?.roleTitle || "Selected Role";
    const missingSkills = Array.isArray(payload?.missingSkills) ? payload.missingSkills : [];
    const content = [
      "SmartHire - Personalized Learning Roadmap",
      `Role: ${roleTitle}`,
      `Generated At: ${new Date().toLocaleString()}`,
      "",
      `Skills to Focus: ${missingSkills.join(", ") || "None"}`,
      "",
      "Roadmap:",
      ...roadmap.map((step, idx) => `${idx + 1}. ${step}`),
      "",
      "Generated by SmartHire AI Assistant",
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const link = document.createElement("a");
    const safeRole = String(roleTitle).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    link.href = URL.createObjectURL(blob);
    link.download = `smarthire-roadmap-${safeRole || "role"}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
  };

  return (
    <div className="space-y-5">
      <section className="rounded-2xl border border-[#dbe7ff] bg-gradient-to-r from-[#eef4ff] via-white to-[#f7f9ff] p-5 shadow-sm">
        <p className="text-sm font-medium text-[#2f58c6]">AI Learning Assistant</p>
        <h2 className="mt-1 text-2xl font-semibold text-[#1d2b5d]">Personalized Learning Roadmap</h2>
        <p className="mt-2 text-sm text-slate-600">
          Built for role: <span className="font-medium">{payload?.roleTitle || "Selected Role"}</span>
        </p>
      </section>

      {loading && (
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="h-6 w-6 animate-spin rounded-full border-2 border-[#1e3a8a] border-t-transparent" />
            <p className="text-sm text-slate-600">Generating your roadmap with AI...</p>
          </div>
        </section>
      )}

      {!loading && error && (
        <section className="space-y-3 rounded-2xl border border-red-200 bg-red-50 p-5 shadow-sm">
          <p className="text-sm text-red-700">{error}</p>
          <button
            type="button"
            onClick={() => navigate("/resume-analysis")}
            className="rounded-lg bg-[#1e3a8a] px-3.5 py-2 text-sm font-medium text-white transition hover:bg-[#2849aa]"
          >
            Back to Resume Analysis
          </button>
        </section>
      )}

      {!loading && !error && (
        <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          {!!warning && (
            <p className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-700">
              {warning}
            </p>
          )}
          <div className="rounded-xl border border-amber-100 bg-amber-50 p-4">
            <p className="text-sm font-semibold text-amber-700">Skills to Focus</p>
            <p className="mt-1 text-sm text-amber-800">
              {(payload?.missingSkills || []).join(", ") || "No missing skills"}
            </p>
          </div>
          <RoadmapCard items={roadmap} />
          <div className="flex flex-wrap items-center gap-2">
            <button
              type="button"
              onClick={downloadRoadmap}
              disabled={!roadmap.length}
              className="rounded-lg bg-[#1e3a8a] px-3.5 py-2 text-sm font-medium text-white transition hover:bg-[#2849aa] disabled:cursor-not-allowed disabled:opacity-50"
            >
              Download Roadmap
            </button>
            <Link
              to="/resume-analysis"
              className="inline-block rounded-lg border border-slate-300 px-3.5 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
            >
              Back to Resume Analysis
            </Link>
          </div>
        </section>
      )}
    </div>
  );
}

export default LearningRoadmap;
